### ISSUE TITLE
Feature request: dealing with youtube shorts

### ISSUE THREAD

**Issue by jumeitent** [justinribeiro/lite-youtube#64]
Could you add a feature that can handle the Youtube shorts video?
Thank you in advance!

**Comment by jumeitent** [comment]
Thank you!

**Comment by kamerat** [comment]
It seems if you just swap the height and width of the youtube embed and add a YouTube Short id, the youtube embed player will show as a "shorts player":

![image](https://github.com/user-attachments/assets/47419aee-ed77-4226-adc0-98ffd06c3e4e)


the short prop you added does not seem to work for me.

Workaround I've done is added some css to change aspect-ratio and max-width of the youtube-lite player to make it go in to short mode:

FYI; `.short` is a class I added on the wrapper if the video-url includes "shorts".

```css
.video-wrapper {
  &.short {
      max-width: 450px;
      .youtube {
          aspect-ratio: 9 / 16;
      }
  }
}
```

I believe this works ok, but ideally the youtube player icon should have been the youtube shorts one as the video above and maybe there's a different thumbnail picture for shorts? 🤷 Just putting this here in case somebody else needs this.
